In [1]:
import numpy as np

In [7]:
# -- 3.1 1D NumPy Arrays --
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr), np.argmax(arr))
print(np.min(arr), np.max(arr)) # These do match from the previous step.
print(arr[arr > 20])

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6 7
4 50
[27 31 50 39 35]


In [20]:
# -- 3.2 2D NumPy Arrays --
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 110]
]
matrix = np.array(matrix)

print(np.shape(matrix))
print(matrix[:, 2])
print(matrix[1, :])
print(matrix * 2)
print(matrix.mean(axis = 0))
print(matrix.mean())
print(matrix.max(axis = 1))
print(matrix.min(axis = 0))
print(matrix.flatten()) # The new shape is just one line. It is not a matrix anymore, it is just one list.
print(np.argmin(matrix), np.argmax(matrix))
print(np.unravel_index(np.argmin(matrix), matrix.shape))
print(np.unravel_index(np.argmax(matrix), matrix.shape))
boolean = matrix > 15
print(matrix[boolean])
print(np.sort(matrix, axis = 1))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[ 10  24  34  18]
 [ 16  42  28   6]
 [ 12  26  38 220]]
[ 6.33333333 15.33333333 16.66666667 40.66666667]
19.75
[ 17  21 110]
[ 5 12 14  3]
[  5  12  17   9   8  21  14   3   6  13  19 110]
7 11
(np.int64(1), np.int64(3))
(np.int64(2), np.int64(3))
[ 17  21  19 110]
[[  5   9  12  17]
 [  3   8  14  21]
 [  6  13  19 110]]


In [22]:
# -- 4 Prime Star Systems -- 
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def prime_number(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def sort_prime_rows(arr):
    prime_rows = []
    for row in arr:
        for num in row:
            if prime_number(num):
                prime_rows.append(row)
                break
    return np.array(prime_rows)
print(sort_prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [30]:
# -- 5 Let's Play Checkers! --
def checkerboard():
    board = np.zeros((8,8), dtype=int)
    board[0::2, 0::2] = 1
    board[1::2, 1::2] = 1
    return board

def reversed_checkerboard():
    board = np.zeros((8,8), dtype=int)
    board[1::2, 0::2] = 1
    board[0::2, 1::2] = 1
    return board

In [31]:
# -- 6 The Expanding Universe -- 
def expansion(s, n):
    expanded_string = ""
    for char in s:
        expanded_string += char + " " * n
    return expanded_string.rstrip()

In [ ]:
# -- 7 Second-Brightest Star --
def second_brightest_star(stars):
    second_brightest_star = []
    for clister in stars:
        sorted_cluster = sorted(cluster, reverse = True)
        second_brightest_star.append(sorted_cluster[1])
    return second_brightest_star